[".oh-my-zsh/custom/plugins/zsh-autosuggestions"]
    type = "git-repo"
    url = "https://github.com/zsh-users/zsh-autosuggestions.git"
    refreshPeriod = "168h"
    [".oh-my-zsh/custom/plugins/zsh-autosuggestions".pull]
        args = ["--ff-only"]

[".oh-my-zsh/custom/plugins/zsh-autocomplete"]
    type = "git-repo"
    url = "https://github.com/marlonrichert/zsh-autocomplete.git"
    refreshPeriod = "168h"
    [".oh-my-zsh/custom/plugins/zsh-autocomplete".pull]
        args = ["--ff-only"]

[".oh-my-zsh/custom/plugins/fast-syntax-highlighting"]
    type = "git-repo"
    url = "https://github.com/zdharma-continuum/fast-syntax-highlighting.git"
    refreshPeriod = "168h"
    [".oh-my-zsh/custom/plugins/fast-syntax-highlighting".pull]
        args = ["--ff-only"]

[".oh-my-zsh/custom/plugins/you-should-use"]
    type = "git-repo"
    url = "https://github.com/MichaelAquilina/zsh-you-should-use.git"
    refreshPeriod = "168h"
    [".oh-my-zsh/custom/plugins/you-should-use".pull]
        args = ["--ff-only"]

[".oh-my-zsh/custom/plugins/ohmyzsh-full-autoupdate"]
    type = "git-repo"
    url = "https://github.com/Pilaton/OhMyZsh-full-autoupdate.git"
    refreshPeriod = "168h"
    [".oh-my-zsh/custom/plugins/ohmyzsh-full-autoupdate".pull]
        args = ["--ff-only"]

[".oh-my-zsh/custom/plugins/zsh-lsd"]
    type = "git-repo"
    url = "https://github.com/z-shell/zsh-lsd.git"
    refreshPeriod = "168h"
    [".oh-my-zsh/custom/plugins/zsh-lsd".pull]
        args = ["--ff-only"]

[".oh-my-zsh/custom/plugins/zsh-bat"]
    type = "git-repo"
    url = "https://github.com/fdellwing/zsh-bat.git"
    refreshPeriod = "168h"
    [".oh-my-zsh/custom/plugins/zsh-bat".pull]
        args = ["--ff-only"]

[".oh-my-zsh/custom/plugins/zsh-256color"]
    type = "git-repo"
    url = "https://github.com/chrissicool/zsh-256color.git"
    refreshPeriod = "168h"
    [".oh-my-zsh/custom/plugins/zsh-256color".pull]
        args = ["--ff-only"]

[".oh-my-zsh/custom/themes/spaceship-prompt"]
    type = "git-repo"
    url = "https://github.com/spaceship-prompt/spaceship-prompt.git"
    refreshPeriod = "168h"
    [".oh-my-zsh/custom/themes/spaceship-prompt".pull]
        args = ["--ff-only"]